loginProject/loginProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('loginapp.urls')),
]

loginProject/loginapp/urls.py
from django.conf.urls import url 
from django.urls import path 
from loginapp import views

app_name = "loginapp"

urlpatterns = [
   path('', views.index, name = 'index'),
   path('register/', views.register, name = 'register'),
   path('login/', views.login_page, name = 'login'),
   path('user-login/', views.login_user, name = 'login_user'),
   path('user-logout/', views.user_logout, name = 'logout'),
]

loginProject/loginapp/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

class Userinfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)

    def __str__(self):
        return self.user.username

loginProject/loginapp/forms.py
from django import forms
from django.contrib.auth.models import User 
from .models import Userinfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class UserinfoForm(forms.ModelForm):
    class Meta():
        model = Userinfo
        fields = ('facebook_id', 'profile_pic')

loginProject/loginapp/views.py
from django.shortcuts import render
from .forms import UserForm, UserinfoForm
from .models import Userinfo

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse 
from django.urls import reverse

# Create your views here.

def index(request):
    diction = {}
    return render(request, 'loginapp/index.html', context = diction)

def login_page(request):
    return render(request, 'loginapp/login.html', context = {})

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('loginapp:index'))
            
            else:
                return HttpResponse("Account is not active!!")
        
        else:
            return HttpResponse("Login details are wrong!!")
    
    else:
        return HttpResponseRedirect(reverse('loginapp:login'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('loginapp:index'))

def register(request):
    registered = False 

    if request.method == 'POST':
        user_form = UserForm(data= request.POST)
        user_info_form = UserinfoForm(data= request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']
            
            user_info.save()
            registered = True 
    
    else:
        user_form = UserForm()
        user_info_form = UserinfoForm()
    
    diction = {'userform':user_form, 'userinfo_form':user_info_form, 'registered':registered}
    return render(request, 'loginapp/register.html', context= diction)

loginProject/templates/loginapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{ title }} </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'loginapp:index' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li>
                <a class="nav-link" href="{% url 'loginapp:logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
                <a class="nav-link" href="{% url 'loginapp:register' %}">Register</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'loginapp:login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </nav>

    <div class="container" style="padding-top: 20px; ">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>

loginProject/templates/loginapp/index.html
{% extends 'loginapp/base.html' %}
{% block body_block %}
<h2>This is index page</h2>
{% endblock %}

loginProject/templates/loginapp/login.html
{% extends 'loginapp/base.html' %}

{% block body_block %}
<h3>Please Login:</h3>
<form action="{% url 'loginapp:login_user' %}" method="POST">
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter username.." required
    class="form-control">
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Enter password.." required
    class="form-control">
    {% csrf_token %}
    <br>
    <input type="submit" name="submit" value="Login">
</form>
{% endblock %}

loginProject/templates/loginapp/register.html
{% extends 'loginapp/base.html' %}
{% load static %}

{% block body_block %}

{% if registered %}
<div class="alert alert-success">Congratulations! Registration successfull</div>
{% else %}
<form method="POST" enctype="multipart/form-data">
    {{ userform.as_p }}
    {{ userinfo_form.as_p }}
    {% csrf_token %}
    <button type="submit">Register</button>
</form>
{% endif %}

{% endblock %}